[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
program_registry = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
parameter_storage = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnT"
core_markets = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnU"
market_resolution = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnV"
proposal_system = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnW"
bond_manager = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnX"

[programs.devnet]
program_registry = "2ysaGgXXKK7fTjKp59nVyivP7yoUpf9QHJqQHAuavchP"
parameter_storage = "J63ypBPAjWEMrwyFxWTP6vG8tGF58gH8w9G6yjDFqumD"
core_markets = "6BBZWsJZq23k2NX3YnENgXTEPhbVEHXYmPxmamN83eEV"
market_resolution = "Hcxxt6W1HmKQmnUvqpgzNEqVG611Yzt2i4DUvwvkLRf2"
proposal_system = "5XH5i8dypiB4Wwa7TkmU6dnk9SyUGqE92GiQMHypPekL"
bond_manager = "8XvCToLC42ZV4hw6PW5SEhqDpX3NfqvbAS2tNseG52Fx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
